
create table TEACHERS (
  TEACHER_ID SERIAL,
  TEACHER_NAME CHARACTER VARYING(64),
  TEACHER_EMAIL CHARACTER VARYING(512),
  TEACHER_PHONE CHARACTER VARYING(64),
  PRIMARY KEY (TEACHER_ID)
); 


drop table TEACHERS;